---
- name: Install PostgreSQL 14
  hosts: db_server
  become: yes  # Use sudo
  vars:
    postgresql_version: 14
    root_password: "{{ root_user_password }}"  # Password should be passed from Terraform
    application_user: nextcloud
    application_password: "{{ nextcloud_password }}"  # Password should be passed from Terraform
    application_db: nextclouddb
    cluster_datastore_user: cluster
    cluster_datastore_password: "{{ cluster_password }}"  # Password should be passed from Terraform
    cluster_datastore_db: clusterdb
  tasks:
    - name: Debug root_password
      debug:
        var: root_password

    - name: Update apt cache
      apt: update_cache=yes

    - name: Add the PostgreSQL APT key
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Add the PostgreSQL APT repositories
      apt_repository:
        repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main
        state: present

    - name: Update apt cache
      apt: update_cache=yes

    - name: Install PostgreSQL
      apt:
        name: postgresql-{{ postgresql_version }}
        state: present

    - name: Ensure PostgreSQL is listening on *
      lineinfile:
        dest: /etc/postgresql/14/main/postgresql.conf
        regexp: '^listen_addresses\s*='
        line: "listen_addresses='*'"
        state: present
      notify: Restart Postgresql

    - name: Add new configuration to "pg_hba.conf"
      blockinfile:
        dest: /etc/postgresql/14/main/pg_hba.conf
        block: |
          host    all             all             10.0.1.0/24                scram-sha-256
          host    all             all             0.0.0.0/0                  reject      
      notify: Restart Postgresql
    
    - name: Set password for the default PostgreSQL user
      shell: 'psql -c "ALTER USER postgres WITH PASSWORD {{ root_password }};"'

    - name: Create a cluster database
      become_user: postgres
      postgresql_db:
        name: "{{ cluster_datastore_db }}"
        owner: "{{ cluster_datastore_user }}"
        state: present

    - name: Create a cluster database user with limited privileges
      become_user: postgres
      postgresql_user:
        name: "{{ cluster_datastore_user }}"
        password: "{{ cluster_datastore_password }}"
        priv: "{{ cluster_datastore_db }}.*:ALL"
        role_attr_flags: ''
        state: present

    - name: Create an application database
      become_user: postgres
      postgresql_db:
        name: "{{ application_db }}"
        owner: "{{ application_user }}"
        state: present

    - name: Create an application database user with limited privileges
      become_user: postgres
      postgresql_user:
        name: "{{ application_user }}"
        password: "{{ application_password }}"
        priv: "{{ application_db }}.*:ALL"
        role_attr_flags: ''
        state: present

  handlers:
    - name: Restart Postgresql
      systemd:
        name: postgresql
        state: restarted

    - name: Start Postgresql
      systemd:
        name: postgresql
        state: started

    - name: Stop Postgresql
      systemd:
        name: postgresql
        state: stopped

    - name: Enable Postgresql
      systemd:
        name: postgresql
        enabled: yes
